# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'POS Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Label Produk
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 110, 55, 16))
        self.label.setObjectName("label")

        # Dropdown Produk
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 110, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Pilih Produk", "Buku - Rp 8.000", "Pensil - Rp 3.000", "Bolpoin - Rp 5.000", "Tip-Ex - Rp 7.000", "Penggaris - Rp 5.000"])

        # Label Quantity
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 55, 16))
        self.label_2.setObjectName("label_2")

        # Input Quantity (QLineEdit)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 150, 131, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Masukkan jumlah")

        # Label Diskon
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 190, 55, 16))
        self.label_3.setObjectName("label_3")

        # Dropdown Diskon
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(350, 190, 73, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItems(["0%", "10%", "20%", "30%"])

        # Tombol Add to Cart
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(202, 230, 111, 28))
        self.pushButton.setObjectName("pushButton")

        # Tombol Clear
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 230, 81, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        # Area Cart
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(173, 276, 491, 141))
        self.textEdit.setObjectName("textEdit")

        # Label Total Harga
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 430, 481, 16))
        self.label_4.setObjectName("label_4")
        self.label_4.setText("Total: Rp. 0 (0 barang)")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 301, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 371, 16))
        self.label_6.setObjectName("label_6")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
        self.pushButton.clicked.connect(self.add_to_cart)  
        self.pushButton_2.clicked.connect(self.clear_form)  

       
        self.cart_items = []  
        self.total_amount = 0 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POS System"))
        self.label.setText(_translate("MainWindow", "Product"))
        self.label_2.setText(_translate("MainWindow", "Quantity"))
        self.label_3.setText(_translate("MainWindow", "Discount"))
        self.pushButton.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.label_5.setText(_translate("MainWindow", "Nama: Adina Ayu Daraswita"))
        self.label_6.setText(_translate("MainWindow", "NIM: F1D022030"))

    def add_to_cart(self):
        """ Fungsi untuk menambahkan barang ke cart dan menghitung total harga keseluruhan """
        product_text = self.comboBox.currentText()
        quantity_text = self.lineEdit.text()
        discount_text = self.comboBox_3.currentText()

        if product_text == "Pilih Produk" or not quantity_text.isdigit() or int(quantity_text) <= 0:
            self.label_4.setText("Invalid input")
            return

        quantity = int(quantity_text)

    
        price = int(product_text.split("Rp ")[1].replace(".", ""))

        
        discount = int(discount_text.replace("%", ""))

        total_price = (price * quantity) * (1 - discount / 100)

      
        item = f"{product_text} x {quantity} (Diskon: {discount}%) = Rp {int(total_price)}"
        self.cart_items.append(item)

        self.total_amount += int(total_price)

        self.textEdit.setText("\n".join(self.cart_items))
        self.label_4.setText(f"Total: Rp. {self.total_amount} ({len(self.cart_items)} barang)")

    
        self.comboBox.setCurrentIndex(0)
        self.lineEdit.clear()
        self.comboBox_3.setCurrentIndex(0)

    def clear_form(self):
        """ Fungsi untuk mereset form input ke default """
        self.comboBox.setCurrentIndex(0)
        self.lineEdit.clear()
        self.comboBox_3.setCurrentIndex(0)
        self.textEdit.clear()
        self.label_4.setText("Total: Rp. 0 (0 barang)")

        
        self.cart_items.clear()
        self.total_amount = 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
